AgendaD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(("Contact.urls", 'contact'), namespace="contact")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Auth/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
	path("", views.Login, name="Auth"),
	path("login/", views.Login, name="Login"),
	path("logout/", views.Logout, name="Logout"),
	path("register/", views.Register, name="Register"),
]

Contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.index, name="index"),
	path("create/", views.ContactCreate.as_view(), name="create"),
	path("delete/<slug:id>/", views.ContactDelete.as_view(), name="delete"),
	path("update/<slug:id>/", views.ContactUpdate.as_view(), name="update"),
]

Contact/models.py
# Django Contact Models

from django.db import models
from django.contrib.auth.models import User

class Contact(models.Model):
	# Models Structure
	
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	number = models.IntegerField()
	email = models.EmailField(blank=True, null=True)
	image = models.ImageField(upload_to="contact_photos/", blank=True, null=True)
	
	def __str__(self):
		# return firstname and lastname on the admin
		return "{} {}".format(self.first_name, self.last_name)

Contact/forms.py
# Django Contact Form 
from django import forms 

# Contact Model
from .models import Contact

# Contact Form
class ContactForm(forms.ModelForm):
  # Class 'Meta' is required for use ModelForm
  class Meta:
    model = Contact
    fields = [
      'user',
      'first_name',
      'last_name',
      'email',
      'number',
      'image',
    ]

    widgets = {
      'user': forms.Select(
        attrs={'type':'hidden'}
      )
    }

Contact/views.py
# Contact View.py

# Django Libraries
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView

# Contact Model
from .models import Contact

# Contact Form
from .forms import ContactForm

# Function Index for display contacts
def index(request):
	user = request.user
	contacts = Contact.objects.filter(user=user)
	return render(request, "contact/index.html", 
		{
			"contacts": contacts,
			"user": user,
		} 
	)

# Class Based View for create a Contact
class ContactCreate(CreateView):	
	model = Contact
	fields = [
		'user',
		'first_name',
		'last_name',
		'number',
		'email',
		'image',
	]
	template_name = 'contact/create.html'
	success_url = reverse_lazy('contact:index')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user'] = self.request.user
		return context

class ContactDelete(DeleteView):
	model = Contact
	template_name = 'contact/delete.html'
	success_url = reverse_lazy('contact:index')
	slug_field = 'id'
	slug_url_kwarg = 'id'

class ContactUpdate(UpdateView):
	model = Contact
	fields = [
		'first_name',
		'last_name',
		'number',
		'email',
		'image',
	]
	template_name = "contact/update.html"
	success_url = reverse_lazy('contact:index')
	slug_field = 'id'
	slug_url_kwarg = 'id'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>AgendaD</title>
</head>
<body>
  
  {% block content %}{% endblock %}

</body>
</html>

templates/contact/contacts.html
{% for contact in contacts %}
	
<h2>{{ contact.first_name }} {{ contact.last_name }}</h2>
<h3>Número: {{ contact.number }}</h3>

{% if contact.email %}
  <h3>Correo: {{ contact.email }}</h3>
{% endif %}

{% if contact.image %}
  <img style="width: 300px" src="{{ MEDIA_URL }}{{ contact.image }}" alt="image">
{% endif %}

<h3>
  <a href="{% url 'contact:update' contact.id %}">Editar</a> 
  <a href="{% url 'contact:delete' contact.id %}">Borrar</a>
</h3>

<br>

{% endfor %}

templates/contact/create.html
<form action="{% url 'contact:create' %}" method="POST" enctype="multipart/form-data">

	{% csrf_token %}
	
	{% comment %}
	{% endcomment %}
	<input type="hidden" name="user" value="{{ user.pk }}">
	
	<label for="first_name">Nombre</label>
	<input type="text" name="first_name" id="first_name">
	
	<label for="last_name">Apellido</label>
	<input type="text" name="last_name" id="last_name">
	
	<label for="number">Numero</label>
	<input type="number" name="number" id="number">
	
	<label for="email">Correo</label>
	<input type="email" name="email" id="email">
	
	<label for="image">Imagen</label>
	<input type="file" name="image" id="image">

	<button type="submit">Guardar</button>
	
</form>

templates/contact/delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>

templates/contact/detail.html
<h2>{{ object.first_name }} {{ object.last_name }}</h2>
<h3>Número: {{ object.number }}</h3>

{% if object.email %}
  <h3>Correo: {{ object.email }}</h3>
{% endif %}

{% if object.image %}
  <img style="width: 300px" src="{{ MEDIA_URL }}{{ object.image }}" alt="image">
{% endif %}

<h3><a href="{% url 'contact:delete' object.id %}">Borrar</a></h3>

templates/contact/index.html
{% extends "base.html" %}

{% block content %}

	<h1>Hola {{ user }}</h1>

	{% include 'contact/create.html' %}
	
	<h2>Mis contactos:</h2>
	
	{% include 'contact/contacts.html' %}
	
{% endblock  %}

templates/contact/update.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>